version: "3.7"
services:
    app:
        build: ./src
        ports:
            - "80:8080"
        volumes:
            - /root/logs/main:/home/App/Logs
        network_mode: "host"
        restart: always
        tty: true
