version: "3.7"
services:
    app:
        build: ./src
        ports:
            - "5010:5010"
        volumes:
            - /root/logs/xuemc:/home/xuemc/Logs
        network_mode: "host"
        restart: always
        tty: true
